apiVersion: v1
kind: Service
metadata:
  name: {{ include "mssql.fullname" . }}-lb
  labels:
    {{- include "mssql.labels" . | nindent 4 }}
spec:
  type: LoadBalancer
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "mssql.selectorLabels" . | nindent 4 }}
