{{- if empty .Values.mirror0_service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mssql.fullname" . }}-mirror-0
spec:
  selector:
    statefulset.kubernetes.io/pod-name: mssql-0
  ports:
  - protocol: TCP
    port: 5022
    targetPort: 5022
{{- end }}    
{{- if empty .Values.mirror1_service.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mssql.fullname" . }}-mirror-1
spec:
  selector:
    statefulset.kubernetes.io/pod-name: mssql-1
  ports:
  - protocol: TCP
    port: 5022
    targetPort: 5022
{{- end }}
{{- if empty .Values.mirror2_service.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mssql.fullname" . }}-mirror-2
spec:
  selector:
    statefulset.kubernetes.io/pod-name: mssql-2
  ports:
  - protocol: TCP
    port: 5022
    targetPort: 5022
{{- end }}