apiVersion: v1
kind: Service
metadata:
  name: {{ include "mssql.fullname" . }}-lb-0
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    statefulset.kubernetes.io/pod-name: {{ include "mssql.fullname" . }}-0
  ports:
  - protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.containers.ports.containerPort}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mssql.fullname" . }}-lb-1
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    statefulset.kubernetes.io/pod-name: {{ include "mssql.fullname" . }}-1
  ports:
  - protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.containers.ports.containerPort}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mssql.fullname" . }}-lb-2
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    statefulset.kubernetes.io/pod-name: {{ include "mssql.fullname" . }}-2
  ports:
  - protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.containers.ports.containerPort}}
